before_script:
  - docker-compose -v

stages:
  - release-bcfastapi
  - release-bcfastapi-test
release-bcfastapi:
  stage: release-bcfastapi
  tags:
    - "fastapi"
  only:
    - main
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer" | bash
    - docker-compose -f docker-compose.yml up -d --build

release-bcfastapi-test:
  stage: release-bcfastapi-test
  tags:
    - "fastapitest"
  only:
    - dev
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer" | bash
    - docker-compose -f docker-compose.yml up -d --build