version: '2.2'

services:
  bcfastapi:
    image: fastapi
    container_name: bcfastapi
    hostname: bcfastapi
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
    - 4000:4000
    # network_mode: host
    
    mem_limit: "8g"

